
if 0:
    import asyncio
    import collections
    import concurrent
    #import ctypes
    #import curses
    import dbm
    import distutils
    import email
    import encodings
    import ensurepip
    import html
    import http
    import idlelib
    import importlib
    import json
    import lib2to3
    import logging
    #import msilib
    import multiprocessing
    import pydoc_data
    #import sqlite3
    import test
    #import tkinter
    import turtledemo
    import unittest
    import urllib
    import venv
    import wsgiref
    import xml
    import xmlrpc
    import abc
    import aifc
    import antigravity
    import argparse
    import ast
    import asynchat
    import asyncore
    import base64
    import bdb
    import binhex
    import bisect
    #import bz2
    import calendar
    import cgi
    import cgitb
    import chunk
    import cmd
    import code
    import codecs
    import codeop
    import colorsys
    import compileall
    import configparser
    import contextlib
    import copy
    import copyreg
    import cProfile
    #import crypt
    import csv
    import datetime
    import decimal
    import difflib
    import dis
    import doctest
    import dummy_threading
    import enum
    import filecmp
    import fileinput
    import fnmatch
    import formatter
    import fractions
    import ftplib
    import functools
    import genericpath
    import getopt
    import getpass
    import gettext
    import glob
    import gzip
    import hashlib
    import heapq
    import hmac
    import imaplib
    import imghdr
    import imp
    import inspect
    import io
    import ipaddress
    import keyword
    import linecache
    import locale
    #import lzma
    import macpath
    import macurl2path
    import mailbox
    import mailcap
    import mimetypes
    import modulefinder
    import netrc
    import nntplib
    import ntpath
    import nturl2path
    import numbers
    import opcode
    import operator
    import optparse
    import os
    import pathlib
    import pdb
    import pickle
    import pickletools
    import pipes
    import pkgutil
    import platform
    import plistlib
    import poplib
    import posixpath
    import pprint
    import profile
    import pstats
    #import pty
    import py_compile
    import pyclbr
    import pydoc
    import queue
    import quopri
    import random
    import re
    import reprlib
    import rlcompleter
    import runpy
    import sched
    import secrets
    import selectors
    import shelve
    import shlex
    import shutil
    import signal
    import site
    import smtpd
    import smtplib
    import sndhdr
    import socket
    import socketserver
    import sre_compile
    import sre_constants
    import sre_parse
    #import ssl
    import stat
    import statistics
    import string
    import stringprep
    import struct
    import subprocess
    import sunau
    import symbol
    import symtable
    import sysconfig
    import tabnanny
    import tarfile
    import telnetlib
    import tempfile
    import textwrap
    import this
    import threading
    import timeit
    import token
    import tokenize
    import trace
    import traceback
    import tracemalloc
    #import tty
    #import turtle
    import types
    import typing
    import uu
    import uuid
    import warnings
    import wave
    import weakref
    import webbrowser
    import xdrlib
    import zipapp
    import zipfile
    import __future__
    import _bootlocale
    import _collections_abc
    import _compat_pickle
    import _compression
    import _dummy_thread
    import _markupbase
    import _osx_support
    import _pydecimal
    import _pyio
    import _sitebuiltins
    import _strptime
    import _threading_local
    import _weakrefset

def on_app_open():
    print("on_app_open")

    
def on_app_close():
    print("on_app_close")
